shelf:
  color_path: simple_calibration_Color_1600.png
  depth_path: simple_calibration_Depth_1900.csv
products:
  - product_1:
      color_path: simple_calibration_Color_1800.png 
      depth_path: simple_calibration_Depth_2200.csv 
  - product_2:
      color_path: simple_calibration_Color_2000.png 
      depth_path: simple_calibration_Depth_2400.csv 
  - product_3:
      color_path: simple_calibration_Color_2201.png 
      depth_path: simple_calibration_Depth_2601.csv 
  - product_4:
      color_path: simple_calibration_Color_2500.png 
      depth_path: simple_calibration_Depth_2800.csv 
  - product_5:
      color_path: simple_calibration_Color_2700.png 
      depth_path: simple_calibration_Depth_3001.csv 
  - product_6:
      color_path: simple_calibration_Color_2900.png 
      depth_path: simple_calibration_Depth_3200.csv 
  - product_7:
      color_path: simple_calibration_Color_3100.png 
      depth_path: simple_calibration_Depth_3400.csv 
  - product_8:
      color_path: simple_calibration_Color_3300.png 
      depth_path: simple_calibration_Depth_3600.csv 
